language: c
sudo: false
cache: false

env:
  global:
    - RACKET_DIR=~/racket
    - DISPLAY=:99.0            # needed by the unit tests, see comment on xvfb
  matrix:
    - RACKET_VERSION=7.0

matrix:
  allow_failures:
    - env: RACKET_VERSION=HEAD
    - env: RACKET_VERSION=RELEASE 
  fast_finish: true

before_install:
  - bash ./.travis/install-racket.sh
  - export PATH="${RACKET_DIR}/bin:${PATH}"
install: true
before_script:
script:
  - raco pkg install --deps search-auto
  - raco setup --check-pkg-deps --pkgs data-frame
  - raco test --no-run-if-absent --package data-frame
after_success:
